# add ~/.bash_profile if needed for executing ~/.bashrc
if [ -e ~/.bashrc -a ! -e ~/.bash_profile -a ! -e ~/.bash_login -a ! -e ~/.profile ]; then
  printf "\n\033[31mWARNING: Found ~/.bashrc but no ~/.bash_profile, ~/.bash_login or ~/.profile.\033[m\n\n"
  echo "This looks like an incorrect setup."
  echo "A ~/.bash_profile that loads ~/.bashrc will be created for you."
  cat >~/.bash_profile <<-\EOF
	# generated by Git for Windows
	test -f ~/.profile && . ~/.profile
	test -f ~/.bashrc && . ~/.bashrc
	EOF
fi

export CLASSNAME=`/usr/local/bin/course -v`

# firebase requires System32
PATH=/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/core_perl:/usr/bin/vendor_perl:/C/Windows/System32
export LANG="ja_JP.utf8"
export COURSEYEAR=`/usr/local/bin/course`

mkdir -p "$USERPROFILE/oithomes/magiot/kadai/$COURSEYEAR/.log/"
export NODE_HOME=/c/oit/$COURSEYEAR/`/usr/local/bin/coursenode`
export WINPYTHON_HOME=/c/oit/$COURSEYEAR/`/usr/local/bin/coursewinpython -v`
export PATH=$WINPYTHON_HOME:$WINPYTHON_HOME/`/usr/local/bin/coursewinpython`:$WINPYTHON_HOME/`/usr/local/bin/coursewinpython`/Scripts:$PATH
export PATH=$NODE_HOME:$PATH
export NODE_PATH=$NODE_HOME/node_modules/npm/node_modules:$NODE_HOME/node_modules/npm
export PATH=/c/oit/$COURSEYEAR/`/usr/local/bin/coursevscode`/:$PATH
export HOME=$(cd "$USERPROFILE\oithomes\magiot" && pwd)

# Hidden setting
/c/Windows/System32/attrib.exe +H ~/kadai/${COURSEYEAR}/.log 1>> "$HISTFILE" 2>&1

export HISTDATE=`date +'%Y%m'`
export HISTFILE="$HOME/kadai/$COURSEYEAR/.log/.${CLASSNAME}_bash_history.$HISTDATE"
HISTTIMEFORMAT="%Y/%m/%dT%T%z "
export PROMPT_COMMAND='echo -e "res:$?\tpwd:$PWD" >> ~/kadai/$COURSEYEAR/.log/.${CLASSNAME}_bash_history.$HISTDATE;history -a'

# /home�̍쐬
export MSYS=winsymlinks:lnk
if [ ! -e "/home/${USERNAME}" ]; then
  mkdir -p /home
  ln -s "${HOME}" "/home/${USERNAME}"
fi
